language: go
sudo: false
go_import_path: github.com/gobeam/mongo-go-pagination
go:
  - 1.9
services:
  - mongodb
before_install:
  - go get ./...
  - go get github.com/mattn/goveralls

script:
  - go test -cover -coverprofile=.coverprofile $(go list .)
  - $GOPATH/bin/goveralls -service=travis-ci -coverprofile=.coverprofile
